const sampleData = {
  products: [
    {
      name: "Air Jordan 1 Mid",
      slug: "air-jordan-mid",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 Low",
      slug: "air-jordan-low",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 High",
      slug: "air-jordan-high",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 Mid",
      slug: "air-jordan-mid",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 Low",
      slug: "air-jordan-low",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 High",
      slug: "air-jordan-high",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 Mid",
      slug: "air-jordan-mid",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 Low",
      slug: "air-jordan-low",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
    {
      name: "Air Jordan 1 High",
      slug: "air-jordan-high",
      category: "Men's Shoes",
      description:
        "Inspired by the original AJ1, this mid-top edition maintains the iconic look you love while choice colours and crisp leather give it a distinct identity.",
      images: [
        "/images/sample-products/a-one.png",
        "/images/sample-products/a-two.png",
      ],
      price: 90.99,
      brand: "Jordan",
      rating: 4.8,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-one.png",
    },
  ],
};

export default sampleData;
